### ISSUE TITLE
I want to decrease how often every sickness appears, can you give me a example configuration for this please?

### ISSUE THREAD

**Issue by TheButterbrotMan** [ArtixAllMighty/BadBone#11]
frequencyArthritis = 24000
frequencyHurt = 8000
chanceHurt = 10
frequencyKnee = 10
frequencyEyes = 24000

**Comment by AbsolemJackdaw** [comment]
the numbers are one chance in x. if you want them to be less frequent, pump up the numbers. 

the config file should have a description per element ? 

hurt is the backpack being checked. once its filled over half, it 1 in 8000 chances of hurting you, and if it passes, you got one chance in ten. 

knee frequency is the 1 in 10 chance to get bad knees when jumping down from a ledge. 

your eyes will go bad 1 chance in 24000. 

all these values are mostly calculated while doing an action ,like jumping down, or just walking around. 
if you want it to be more rare, double or triple the values
