### ISSUE TITLE
Request: Trinkets Mod-Compat

### ISSUE THREAD

**Issue by TheButterbrotMan** [ArtixAllMighty/BadBone#12]

**Comment by TheButterbrotMan** [comment]
https://github.com/TheButterbrotMan/Deathdusk/issues/95

**Comment by AbsolemJackdaw** [comment]
so is this a request or participation to a conversation ?

**Comment by TheButterbrotMan** [comment]
Request sorry lol

**Comment by AbsolemJackdaw** [comment]
so you're asking for compatibility with baubles or curios ?

**Comment by TheButterbrotMan** [comment]
For: https://www.curseforge.com/minecraft/mc-mods/trinkets.

**Comment by AbsolemJackdaw** [comment]
decided against it today. 
wearing the glasses itself is also a handicap, and being able to throw on glasses without obstacle defeats the point of the sight issues
