### ISSUE TITLE
Blind incompatible with Shadow

### ISSUE THREAD

**Issue by SeanChengN** [ArtixAllMighty/BadBone#9]
Forge 40.0.49
BadBone-forge-1.18.2-1.1.0.0
ComplementaryShaders_v4.4

If I apply shadow, the blinding effect won't work.
![2022-04-16_11 31 16](https://user-images.githubusercontent.com/20624068/163659894-d4bd2502-f32d-4dd6-86d6-e1ade28c5c9e.png)

**Comment by AbsolemJackdaw** [comment]
You arent wearing glasses right ?
It might be due to the shader. Bluery vision is a shader too, and I wonder if the game cant only run one shader at once.
Ill look into it

**Comment by SeanChengN** [comment]
> 

I'm wearing an iron helmet. Thanks!

**Comment by AbsolemJackdaw** [comment]
In essence, depending on the shaders their is compatibilty. The shadow shader probably also uses the depth buffer the blind effect shader uses, and the game doesnt fuse them. Its just one or the other sadly, so this is intended use somehow ? Eventhough it sucks offcourse. I probably wont be able to do anything about it

**Comment by SeanChengN** [comment]
> In essence, depending on the shaders their is compatibilty. The shadow shader probably also uses the depth buffer the blind effect shader uses, and the game doesnt fuse them. Its just one or the other sadly, so this is intended use somehow ? Eventhough it sucks offcourse. I probably wont be able to do anything about it

It's okay, I can still break my leg😂
